import React from 'react'
import CategoryListing from '../Components/CategoryListing'
import MainLayout from '../Components/Common/MainLayout';

export const metadata = {
  title: "Category Listings",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <MainLayout>
        <CategoryListing/>
      </MainLayout>
      
    </>
  )
}
