import React from 'react'
import CategoryListing from '../Components/CategoryListing'

export const metadata = {
  title: "Category Listings",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <CategoryListing/>
    </>
  )
}
