import React from 'react'
import MainLayout from '../Components/Common/MainLayout';
import Login from '../Components/Login';

export const metadata = {
  title: "Login | MayBell",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <MainLayout>
            <Login/>
      </MainLayout>
    </>
  )
}
