
import React from 'react'
import MainLayout from '../../Components/Common/MainLayout';
import CategoryListing from '../../Components/CategoryListing';

export const metadata = {
  title: "Category Listings",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
      <MainLayout>
        <CategoryListing/>
      </MainLayout>
    </>
  )
}
